spring:
  datasource:
    password: sa
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    hikari:
      auto-commit: false
      driver-class-name: org.h2.Driver

h2:
  console:
  enabled: true
  path: /h2-console